//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wProveedores.WSDBOracle {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSDBOracle.DBOracleSoap")]
    public interface DBOracleSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetData(string cod_empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string cod_empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendData(string cod_empleado, string num_documento, string fecha, string monto, string ingresoDescuento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendData", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendDataAsync(string cod_empleado, string num_documento, string fecha, string monto, string ingresoDescuento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendDataPlanPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendDataPlanPago(string cod_empleado, string descripcion, string fecha, string monto, string ingresoDescuento, string sys_user, string no_cuotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendDataPlanPago", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendDataPlanPagoAsync(string cod_empleado, string descripcion, string fecha, string monto, string ingresoDescuento, string sys_user, string no_cuotas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBOracleSoapChannel : wProveedores.WSDBOracle.DBOracleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBOracleSoapClient : System.ServiceModel.ClientBase<wProveedores.WSDBOracle.DBOracleSoap>, wProveedores.WSDBOracle.DBOracleSoap {
        
        public DBOracleSoapClient() {
        }
        
        public DBOracleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBOracleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBOracleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBOracleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetData(string cod_empleado) {
            return base.Channel.GetData(cod_empleado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string cod_empleado) {
            return base.Channel.GetDataAsync(cod_empleado);
        }
        
        public bool SendData(string cod_empleado, string num_documento, string fecha, string monto, string ingresoDescuento) {
            return base.Channel.SendData(cod_empleado, num_documento, fecha, monto, ingresoDescuento);
        }
        
        public System.Threading.Tasks.Task<bool> SendDataAsync(string cod_empleado, string num_documento, string fecha, string monto, string ingresoDescuento) {
            return base.Channel.SendDataAsync(cod_empleado, num_documento, fecha, monto, ingresoDescuento);
        }
        
        public bool SendDataPlanPago(string cod_empleado, string descripcion, string fecha, string monto, string ingresoDescuento, string sys_user, string no_cuotas) {
            return base.Channel.SendDataPlanPago(cod_empleado, descripcion, fecha, monto, ingresoDescuento, sys_user, no_cuotas);
        }
        
        public System.Threading.Tasks.Task<bool> SendDataPlanPagoAsync(string cod_empleado, string descripcion, string fecha, string monto, string ingresoDescuento, string sys_user, string no_cuotas) {
            return base.Channel.SendDataPlanPagoAsync(cod_empleado, descripcion, fecha, monto, ingresoDescuento, sys_user, no_cuotas);
        }
    }
}
